name: Build

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Dependancies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-oceanchat-cache

    - name: Build Backend
      run: cargo build --features server --profile release-server

    - name: Install Dioxus CLI
      run: |
        if ! command -v dx &> /dev/null; then
          cargo install dioxus-cli
        else
          echo "Dioxus CLI is already installed"
        fi

    - name: Build Frontend
      run: dx build --release
    
    - name: Bundle Build Artifacts
      run: mkdir oceanchat-${{ github.run_number }} && cp -r ./dist ./oceanchat-${{ github.run_number }}/dist && cp ./target/release-server/ocean-chat ./oceanchat-${{ github.run_number }}/ocean-chat

    - name: Upload Bundled Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./oceanchat-${{ github.run_number }}
        name: oceanchat-${{ github.run_number }}
