name: Check

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run cargo check
      run: cargo check
